name: Cleanup Old Workflow Logs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    
    steps:
      - name: Delete workflow runs
        run: |
          REPO=${{ github.repository }}

          gh run list -R $REPO --limit 1000 --status completed --json databaseId --jq '.[].databaseId' \
          | xargs -I {} gh run delete -R $REPO {}
        env:
          GH_TOKEN: ${{ github.token }}
